apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: inference-cluster
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::701262207008:role/LabRole # Update account number
  withOIDC: false

autoModeConfig:
  enabled: false

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    iam:
      instanceRoleARN: arn:aws:iam::701262207008:role/LabRole # Update account number 
