apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      containers:
        - name: consumer
        #Insert info Format: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/<REPO_NAME>:latest
          image: 701262207008.dkr.ecr.us-east-1.amazonaws.com/sqs-consumer:latest 
          env:
            - name: QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/701262207008/test-queue" # update queue URL

            - name: S3_BUCKET
              value: "mlops-final-project331" # update S3 Bucket name

            - name: S3_MODEL_KEY
              value: "models/latest/model.pkl"

            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            
